receivers:
  auditlogreceiver:
    endpoint: 0.0.0.0:4318
    storage: redis_storage
    process_interval: 5s
    process_age_threshold: 5s
    circuit_breaker:
      enabled: false
      circuit_open_threshold: 5
      circuit_open_duration: 1m

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 1000
    sampling_thereafter: 1000

extensions:
  redis_storage:
    endpoint: localhost:6379
    db: 0
    expiration: 24h
    tls:
      insecure: true

service:
  extensions: [redis_storage]
  pipelines:
    logs:
      receivers: [auditlogreceiver]
      exporters: [debug]
